openapi: 3.0.3
info:
  title: Usuários - API Fasil
  version: 1.0.0
  description: Endpoints responsáveis pela gestão de usuários.
servers:
  - url: https://api.fasil.criarsite.online
paths:
  /usuarios:
    get:
      tags: [Usuários]
      summary: Listar todos os usuários
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de usuários
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Usuario'
    post:
      tags: [Usuários]
      summary: Criar novo usuário
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioInput'
      responses:
        '201':
          description: Usuário criado com sucesso
  /usuarios/{id}:
    get:
      tags: [Usuários]
      summary: Obter usuário por ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Dados do usuário
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
    put:
      tags: [Usuários]
      summary: Atualizar usuário
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioInput'
      responses:
        '200':
          description: Usuário atualizado
    delete:
      tags: [Usuários]
      summary: Remover usuário
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Usuário removido com sucesso
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Usuario:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nome:
          type: string
          example: João da Silva
        email:
          type: string
          format: email
          example: joao@email.com
    UsuarioInput:
      type: object
      required:
        - nome
        - email
      properties:
        nome:
          type: string
        email:
          type: string
        senha:
          type: string